### PR TITLE
Add improv-based WiFi provisioning

### PR DESCRIPTION
**Pull request by dkerr64**
* Bugfix: Soft AP list of available WiFi networks not properly terminated
* Bugfix: Setting static IP address did not set correct subnet mask
* Bugfix: Crash in soft AP because memory buffer was not allocated
* Feature: Add support Improv-based WiFi provisioning
* Feature: Add the 10 minute timeout on soft AP mode
* Feature: Add the check for WiFi connectivity 30 seconds after change to static IP

### CODE REVIEW

**Comment by donavanbecker** [comment]
I have a few ESP32 development boards laying around that I can test this on. However I think the only way we could test this is with the flasher would be if we had a pre-release flag on the flasher and we could select that as an option, I feel like that would need to also be in the manifest.json

**Comment by dkerr64** [comment]
It looks like I can test from this web page... https://www.improv-wifi.com/

It is able to connect to me, I am returning SSIDs (too many, need to filter out duplicates from multiple APs) but there is an error when I try and set the SSID & password.  I'll look into that later.

Debugging will be awkward because I can't use serial for logging when it is connected for Improv!

But progress :-)

**Comment by dkerr64** [comment]
Actually, setting SSID and Password is working... but I am not waiting long enough to confirm that.  And they are not being saved across reboot.  So I should be able to get Improv working and tested fairly quickly.  Which provides a smoother way for a user to do the initial provisioning.

**Comment by dkerr64** [comment]
Improv provisioning is now working... at least based on https://www.improv-wifi.com/

I'm ready to merge this if it looks good to others.

**Review by donavanbecker — APPROVED** [review]

**Review by donavanbecker — APPROVED** [review]

**Comment by jgstroud** [comment]
@dkerr64 I'm late to answer, but FYI, there is an improv.py test utility in the 8266 repository.

**Pull request merged**
