### PR TITLE
Fixes and features

### PR DESCRIPTION
**Pull request by dkerr64**
Fixes / features...

- Get OTA update working from GitHub
- Remove (comment out for now) check flash CRC code that will probably never be used on ESP32
- Add audible beeps during time-to-close delay (issue #4)

More TBD...

### CODE REVIEW

**Comment by dkerr64** [comment]
@PaulWieland what should I expect for the distance sensor.  I just added support for it (modeling after your code in ESPhome), see commit in this PR.  But I am not getting any results.  Should I be able to wave my hand above the sensor and have it trigger?  Or does it need to point at something steel/metal?  The loop is basically returning zero objects found.

**Comment by dkerr64** [comment]
@PaulWieland Err, nevermind.  I found a bug in my code.  I am returning from the loop before clearing the interrupt and starting measurement again.  Oops.

**Comment by dkerr64** [comment]
@PaulWieland what algorithm are you using to decide on vehicle presence / arriving / departing and when to turn on/off the laser.  Is there any user settings?

With my DISCO sitting on the workbench and pointing at the ceiling, it is reporting between 1870mm and 1910mm (which feels like longer than actual, but I suppose it is at a slight angle).  But the measurement is constantly changing in this approx 40mm range.

I assume we establish some range that represents GDO to floor, then some other range that represents distance when vehicle is present. then watch for transitions between the too.  Do you do anything to avoid false positives e.g. when there is no vehicle but someone walks under the GDO?

Any thoughts on how to represent this in HomeKit?  I'm thinking of adding an occupancy sensor.

**Comment by PaulWieland** [comment]
All the relevant stuff is basically here:
https://github.com/ratgdo/esphome-ratgdo/blob/f58247e0292de2783a05878fb70c76ece15a4e0d/components/ratgdo/ratgdo.cpp#L382

Cliffs notes:
- add each measurement to a vector of N length (e.g. 30), popping oldest value off as a new value is shifted on
- user adjustable vehicle distance target value since vehicles and ceiling heights are variable
- loop through the vector and detect if a vehicle is present or not by comparing all values in a vector to that of the in range distance set by the user
- if all values are within range, there is a car detected
- if all values are out of range there is no car detected
- if some values are in range or out of rang, there is no state change
- a value of -1 is out of range
- only trigger vehicle arriving / departing within X seconds of the garage door being activated (this is to avoid an accidental false positive turning all the lights on in the house or whatever automation someone has linked to vehicle arriving/leaving)

As far as homekit goes, I haven't tested occupancy sensors. It sounds like a good match as long as an automation can be triggered by the occupancy sensor state change.

I decided to create three boolean sensors in home assistant. vehicle detected, arriving & leaving. Arriving/leaving are set to true by the vehicle detected sensor's state change and they switch back to false after a timeout.

**Comment by dkerr64** [comment]
So, I think I have the vehicle presence, arriving and departing working now.  Including showing status on the web page and allowing user to set a distance threshold.  And I turn on the parking assist laser for 60 seconds when a vehicle arrives.

I have not created HomeKit services for this yet.  But I am considering adding an occupancy sensor to indicate when a vehicle is present, and two motion sensors... one that triggers when a vehicle arrives, other when vehicle departs.

I'm about at the point where I want to mount it on my garage door opener... but for that I need a 50ft USB cable (to replace the serial signals going over a Cat 5 cable).  So far I have gone through two cheep USB extension cables from Amazon and neither have worked... I am creeping up the price point and have ordered a couple more until I find one that works.  Good thing Amazon has easy returns!

**Comment by dkerr64** [comment]
I now have HomeKit accessories added to support vehicle presence and motion.

One thing I learned is that HomeKit requires a "bridge" when more than 3 accessories are present on a device.  So we have a bridge with...

- Garage Door
- Light
- Motion
- Motion for vehicle arriving
- Motion for vehicle departing
- Occupancy for vehicle parked

Introducing a bridge means that if you have already installed this, you will need to remove the accessory from Apple Home and re-pair.  During the pairing process you are prompted to add each device.

I think I am going to merge this so that we have another stake on which to build.

**Pull request merged**
