### PR TITLE
Next batch of updates

### PR DESCRIPTION
**Pull request by dkerr64**
Included so far:

- Only create HomeKit accessories for vehicle presence, arrival and departure if the h/w exists on the ratgdo.
- Add a patch to remove the _request handler not found error_ that is logged to serial port.
- Add code to allow building with a custom ESPIDF ESP32 core, not enabled.

### CODE REVIEW

**Comment by dkerr64** [comment]
@tlhahan I have ported your dry contact code over to the ESP32 codebase.  I did some minor tweaking in the process so I'd appreciate a code review of the [commit above](https://github.com/ratgdo/homekit-ratgdo32/pull/16/commits/4e2c9c58ba58f43d2f13edcf0874c5e7edb00d07).

Also, @PaulWieland while testing comms with HomeKit I saw HomeKit try and unlock the door.  I don't think dry contact will allow lock/unlock so I removed the lock current and target characteristics from the accessory.  Does that sound right?

**Comment by dkerr64** [comment]
@donavanbecker I created a patch to get rid of the horrible _request handler not found_ error in WebServer.  It is in this [commit](https://github.com/ratgdo/homekit-ratgdo32/pull/16/commits/d22218ad9667afbff3e2a18bcf997cd810778a44).

However, the script makes assumptions about the path to that file.  On my system I have...
```
~/.platformio/*
~/github/homekit-ratgdo32/*
```
so when running the patch I use `../../.platformio/etc` in the script.  Which assumes that I am nested two deep from where platformio starts.  This will fail if e.g. folks cloned directly into their home directory rather than nesting under a GitHub directory like me.  And therefore might fail in our release workflow (but I don't think it will be fatal, may just continue the build).

I looked for an environment variable that might point to `~/.platformio` but found nothing.

Do you have any ideas / suggestions?

Thanks.

**Comment by donavanbecker** [comment]
Can we do 

```
../../.platformio/etc ?? ~/.platformio
```

Or something like that?

**Comment by dkerr64** [comment]
> Can we do
> 
> ```
> ../../.platformio/etc ?? ~/.platformio
> ```
> 
> Or something like that?

That gave me an idea.  If .platformio is always under the home directory, then we can use the HOME environment variable.

**Comment by dkerr64** [comment]
I have mounted my ratgdo32 at the GDO (see picture) but now have a problem with the distance sensor. It is reporting completely wrong distances.  With no car parted it is fluctuating between 1-10 inches.  Which is simply wrong.  With car parked it makes no difference.  It was working fine (or so I thought) on the bench pointing at the ceiling.

I mounted it away from the GDO to minimize interference, just-in-case, and I used a compressed air can to dust around the sensor in case it had picked up some dirt, but no change.

@PaulWieland any suggestions?

IMG_7358 Large
IMG_7359 Large

**Comment by dkerr64** [comment]
I also tried calibrating the device and tried distance mode of both medium and long.

  ```
  if (!(bool)nvRam->read(nvram_calibrate_dist))
    {
        // Need to calibrate distance sensor
        RINFO(TAG, "Calibrating VL53L4CX distance sensor");
        rc = distanceSensor.VL53L4CX_PerformRefSpadManagement();
        if (rc != VL53L4CX_ERROR_NONE)
        {
            RERROR(TAG, "VL53L4CX_PerformRefSpadManagement error: %d", rc);
            return;
        }

        VL53L4CX_CalibrationData_t cd;
        rc = distanceSensor.VL53L4CX_GetCalibrationData(&cd);
        if (rc != VL53L4CX_ERROR_NONE)
        {
            RERROR(TAG, "VL53L4CX_GetCalibrationData error: %d", rc);
            return;
        }

        nvRam->write(nvram_calibrate_dist, 1);
        rc = distanceSensor.VL53L4CX_SetCalibrationData(&cd);
        if (rc != VL53L4CX_ERROR_NONE)
        {
            RERROR(TAG, "VL53L4CX_SetCalibrationData error: %d", rc);
            return;
        }
    }
```

And here is some logging of the distance data...

```
max: 26, min: 24, status: 0, dist: 24, exten: 0
max: 24, min: 22, status: 0, dist: 22, exten: 0
max: 22, min: 20, status: 0, dist: 20, exten: 0
max: 26, min: 24, status: 0, dist: 24, exten: 0
max: 23, min: 20, status: 0, dist: 20, exten: 0
max: 25, min: 23, status: 0, dist: 23, exten: 0
max: 24, min: 21, status: 0, dist: 21, exten: 0
max: 1758, min: 1741, status: 7, dist: 1741, exten: 0
max: 24, min: 22, status: 0, dist: 22, exten: 0
max: 1779, min: 1729, status: 7, dist: 1729, exten: 0
max: 25, min: 23, status: 0, dist: 23, exten: 0
max: 1794, min: 1724, status: 7, dist: 1724, exten: 0
max: 22, min: 19, status: 0, dist: 19, exten: 0
max: 1784, min: 1710, status: 7, dist: 1710, exten: 0
max: 23, min: 20, status: 0, dist: 20, exten: 0
max: 23, min: 20, status: 0, dist: 20, exten: 0
max: 23, min: 21, status: 0, dist: 21, exten: 0
max: 24, min: 20, status: 0, dist: 20, exten: 0
max: 22, min: 18, status: 0, dist: 18, exten: 0
max: 25, min: 21, status: 0, dist: 21, exten: 0
max: 22, min: 19, status: 0, dist: 19, exten: 0
max: 24, min: 21, status: 0, dist: 21, exten: 0
max: 21, min: 18, status: 0, dist: 18, exten: 0
max: 23, min: 20, status: 0, dist: 20, exten: 0
max: 23, min: 20, status: 0, dist: 20, exten: 0
max: 25, min: 22, status: 0, dist: 22, exten: 0
max: 24, min: 21, status: 0, dist: 21, exten: 0
```

Those with range status of 7 look believable (distance to the hood of car that is parked below?) but the documentation for that variable states 
```
 /*!< Range Status for the current measurement. This is device
   *  dependent. Value = 0 means value is valid.
   */
```

**Comment by dkerr64** [comment]
Google AI says this... so I should ignore those.

A "distance status 7" on a VL53L4CX sensor typically indicates a "wrapped target fail," meaning the sensor has detected an object that is too close to the sensor or is causing reflections that are wrapping around and interfering with the measurement, making it unable to accurately determine the distance. 
Key points about VL53L4CX distance status 7:
Meaning:
The sensor is unable to get a reliable distance reading due to a target that is too close or causing excessive reflections. 
Potential causes:
Object very close to the sensor 
Highly reflective surfaces causing signal interference 
Multiple objects too close together 
What to do:
Check if the object is too close to the sensor and reposition it further away. 
Consider using a different surface with less reflectivity. 
If necessary, adjust the sensor's settings to try to mitigate the issue.

**Comment by dkerr64** [comment]
When status of 7 comes in, the number of objects detected is > 1.  So have to loop over the array and ignore values with bad status.

But doesn't change that the measurement coming back is wrong.

```
     if ((distanceSensor.VL53L4CX_GetMeasurementDataReady(&dataReady) == 0) && (dataReady > 0))
    {
        VL53L4CX_MultiRangingData_t distanceData;
        VL53L4CX_MultiRangingData_t *pDistanceData = &distanceData;
        if (distanceSensor.VL53L4CX_GetMultiRangingData(pDistanceData) == 0)
        {
            int objCount = pDistanceData->NumberOfObjectsFound;
            for (int i = 0; i < objCount; i++)
            {
                VL53L4CX_TargetRangeData_t d = pDistanceData->RangeData[i];
                Serial.printf("Obj#: %d, max: %d, min: %d, status: %d, dist: %d, exten: %d\n", i, d.RangeMaxMilliMeter, d.RangeMinMilliMeter, d.RangeStatus, d.RangeMilliMeter, d.ExtendedRange);
                if (d.RangeStatus == 0)
                {
                    // Only count it if data valid.
                    calculatePresence(d.RangeMilliMeter);
                }
            }
            distanceSensor.VL53L4CX_ClearInterruptAndStartMeasurement();
        }
    }
```

**Comment by PaulWieland** [comment]
Flash the esphome firmware and see if you get the same distance readings

**Comment by PaulWieland** [comment]
Also - you don’t have any smoke / smog in the garage do you? The laser will bounce off of particles suspended in the air giving a ~20-40mm reading.

**Comment by dkerr64** [comment]
> Flash the esphome firmware and see if you get the same distance readings

Good idea. I’ll do that and report back

**Comment by dkerr64** [comment]
> Also - you don’t have any smoke / smog in the garage do you? The laser will bounce off of particles suspended in the air giving a ~20-40mm reading.

No. Everything is clear.

**Comment by PaulWieland** [comment]
Also make sure it’s aimed at a painted surface and not glass.

**Comment by dkerr64** [comment]
> Flash the esphome firmware and see if you get the same distance readings

ESPhome shows the same problem.

So I did some further debugging.  With reference to this working code segment...
```
        VL53L4CX_MultiRangingData_t distanceData;
        if (distanceSensor.VL53L4CX_GetMultiRangingData(&distanceData) == 0)
        {
            int16_t dist = 0;
            for (int i = 0; i < distanceData.NumberOfObjectsFound; i++)
            {
                VL53L4CX_TargetRangeData_t *d = &distanceData.RangeData[i];
                if (d->RangeStatus == 0)
                {
                    dist = std::max(dist, d->RangeMilliMeter);
                }
            }
            if (dist > 0)
            {
                calculatePresence(dist);
            }
            distanceSensor.VL53L4CX_ClearInterruptAndStartMeasurement();
        }
```
When we get the ranging data it (apparently) can sense multiple objects.  So it returns an array of data with entry for each object (maximum of 4).  There were two errors in the original code... 1) it only looked at the last entry in the array and 2) it ignored the status code.  When I examined the returned values I found that I was consistently getting 2 objects (array elements) returned.  One was consistently in the 20mm range, the other more accurate for the distance I expected.  I was also seeing status return codes of 7 and 4.

As you can see in the above code, what I did was loop through the array, check that the status indicated value was good and only kept the distance for the furthest away object.  Then I only used it if object distance was above zero (to catch cases where all array elements had bad status code.

**Comment by dkerr64** [comment]
@PaulWieland Is it necessary to do any calibration for the distance sensor?  I had tried that during my debugging but it didn't do anything.  I've commented out the code for now but will delete it completely if it is not going to be required.

Now I have this working, I'm ready to merge this PR.

**Comment by PaulWieland** [comment]
This is interesting. I had originally written it to return the largest valid distance found, but through all of the test I did it seemed that the largest distance was _always_ the last distance in the array, so I simplified the code for getting the max distance. For whatever reason in your environment its not behaving that way, so I will bring the change you made into the ESP Home firmware to have it actually find the max distance instead of assuming its the last entry.

**Comment by dkerr64** [comment]
> This is interesting. I had originally written it to return the largest valid distance found, but through all of the test I did it seemed that the largest distance was _always_ the last distance in the array, so I simplified the code for getting the max distance. For whatever reason in your environment its not behaving that way, so I will bring the change you made into the ESP Home firmware to have it actually find the max distance instead of assuming its the last entry.

Yes, I agree.  When I was developing on the bench, using the last member of the array was working.  For some reason when I moved to the garage it did not work.  It is small overhead to look at all returned values and keep only the max... and also to test the status code.

Any thoughts on calibration?

**Comment by PaulWieland** [comment]
Its not necessary to calibrate because the uncalibrated actual distance value is plenty good enough for this application.

**Review by tlhagan — COMMENTED** [review]
The dry contact code all looks correct to me.

If you could change my acknowledgement to Thomas Hagan I'd appreciate it :)

**Comment by tlhagan** [comment]
> > If you could change my acknowledgement to Thomas Hagan I'd appreciate it :)
> 
> Done.

Thanks! The last name is still misspelled though, if you could fix that when you get a chance

**Comment by dkerr64** [comment]
> > > If you could change my acknowledgement to Thomas Hagan I'd appreciate it :)
> > 
> > 
> > Done.
> 
> Thanks! The last name is still misspelled though, if you could fix that when you get a chance

Sorry about that.  I have fixed the spelling and it will go in with the next Pull Request.

**Comment by PaulWieland** [comment]
```
            if (dist > 0)
            {
                calculatePresence(dist);
            }

```

@dkerr64 

How are you handling out of range data?

I ask because in some situations, the floor will be out of range. In the ESP Home firmware I am using -1 whenever things are out of range. I treat consecutive -1 measurements as "no vehicle detected". If you are not calculating presence when nothing is in range, then you might not be updating to "no vehicle detected" when the sensor can't detect the garage floor.

**Comment by PaulWieland** [comment]
> fluctuating between 1-10

I think I figured this out. I bet you have a tiny yellow semi transparent sticker over your sensor that it's detecting and it's reporting # of objects as 1 and a value less than 20mm. Remove the sticker and see what happens....

None the less, I just updated the ESP Home firmware to ignore anything less than 25mm and instead return it as a -1 (which I treat as out of range - aka. no vehicle detected)

**Comment by dkerr64** [comment]
Ah.  Yes I think I may have a sticker on the sensor. I guess it is there to protect it during assembly/shipping. I’ll remove it when I get home.

**Comment by dkerr64** [comment]
@PaulWieland Yes there was a tiny yellow sticker over the sensor.  I have removed it and I do think it has greatly improved the reliability of the data.  Still more testing to confirm that.

As for out-of-range.  I never see a -1 range returned, I have seen negatives accompanied by a bad range status code.  I believe the key is to look at the range status returned.  In testing I am seeing range status of 0, 4, 7 and 12.  These represent...

0:  VL53L4CX_RANGESTATUS_RANGE_VALID
4:  VL53L4CX_RANGESTATUS_OUTOFBOUNDS_FAIL
7:  VL53L4CX_RANGESTATUS_WRAP_TARGET_FAIL
12: VL53L4CX_RANGESTATUS_TARGET_PRESENT_LACK_OF_SIGNAL

Documentation also suggests that valid data can be returned with status codes...

3:  VL53L4CX_RANGESTATUS_RANGE_VALID_MIN_RANGE_CLIPPED
6:  VL53L4CX_RANGESTATUS_RANGE_VALID_NO_WRAP_CHECK_FAIL

I also tested what happens if I point the sensor out into open space (or at least the wall is more than 3 meters away) and the result is that `NumberOfObjectsFound` is set to zero.  It is sometimes preceded by data with status of `VL53L4CX_RANGESTATUS_TARGET_PRESENT_LACK_OF_SIGNAL`

I have updated my code to the following...
```cpp
    uint8_t dataReady = 0;
    if ((distanceSensor.VL53L4CX_GetMeasurementDataReady(&dataReady) == 0) && (dataReady > 0))
    {
        VL53L4CX_MultiRangingData_t distanceData;
        if (distanceSensor.VL53L4CX_GetMultiRangingData(&distanceData) == VL53L4CX_ERROR_NONE)
        {
            if (distanceData.NumberOfObjectsFound > 0)
            {
                int16_t distance = -1;
                // Multiple objects could be found. During testing if I wave my hand in front of the
                // sensor I get two distances... that of my hand, and that of the background.
                // We will only record the furthest away.
                for (int i = 0; i < distanceData.NumberOfObjectsFound; i++)
                {
                    switch (distanceData.RangeData[i].RangeStatus)
                    {
                    case VL53L4CX_RANGESTATUS_RANGE_VALID:
                    case VL53L4CX_RANGESTATUS_RANGE_VALID_MIN_RANGE_CLIPPED:
                    case VL53L4CX_RANGESTATUS_RANGE_VALID_NO_WRAP_CHECK_FAIL:
                        distance = std::max(distance, distanceData.RangeData[i].RangeMilliMeter);
                        break;
                    case VL53L4CX_RANGESTATUS_OUTOFBOUNDS_FAIL:
                    case VL53L4CX_RANGESTATUS_WRAP_TARGET_FAIL:
                    case VL53L4CX_RANGESTATUS_TARGET_PRESENT_LACK_OF_SIGNAL:
                        // Bad data... assume no object, or if is one is past MAX_DISTANCE range.
                        distance = MAX_DISTANCE;
                        break;
                    default:
                        RERROR(TAG, "WARNING: Unhandled VL53L4CX RANGESTATUS value: %d", distanceData.RangeData[i].RangeStatus);
                        break;
                    }
                }
                calculatePresence(distance);
            }
            else
            {
                // No objects found, assume maximum range for purpose of calculating vehicle presence.
                calculatePresence(MAX_DISTANCE);
            }
        }
        // And start the sensor measuring again...
        distanceSensor.VL53L4CX_ClearInterruptAndStartMeasurement();
    }
```

**Comment by PaulWieland** [comment]
> As for out-of-range. I never see a -1 range returned, I have seen negatives accompanied by a bad range status code. I believe the key is to look at the range status returned. In testing I am seeing range status of 0, 4, 7 and 12. These represent...

Yes, I understand that. What I was saying is that if you do not run the calculatePresence function when the data is out of range data, then you can have a situation where no car is present yet the presence never updates to reflect that.

With this original block of code:

```
if (dist > 0)
            {
                calculatePresence(dist);
            }
```

I couldn't see how it would work if the floor was out of range. but the update you posted has an else condition for out of range data. You're using `MAX_DISTANCE` where I'm using `-1` to indicate distance not measurable, but they should both accomplish the same thing.

**Comment by dkerr64** [comment]
Using a MAX_DISTANCE constant works better for my algorithm than -1.

Further testing confirms that the yellow sticker was causing the problems for me... I no longer see bogus distances of ~20 mm, and the distances reported look accurate and reliable.  So long as I don't point it at the car windshield... then I don't get good data.  So I have to angle it to point slightly backwards towards the roof of the car, which reports about 110cm  And the floor is then reported at around 270cm which is further than actual because of the angle.

Your documentation already advises against pointing towards glass windshield, I think we also need to recommend that the yellow sticker is removed.

**Pull request merged**
