### PR TITLE
update flash instructions

### PR DESCRIPTION
**Pull request by PaulWieland**

### CODE REVIEW

**Comment by PaulWieland** [comment]
@dkerr64 is the intention to have this same installer for both ratdo32 and ratgdo32 disco?

**Review by donavanbecker — APPROVED** [review]

**Comment by dkerr64** [comment]
> @dkerr64 is the intention to have this same installer for both ratdo32 and ratgdo32 disco?

I had not given it any thought. But now you mention it yes it would be nice.  We would need to coordinate the manifest file between the repos though?

**Comment by PaulWieland** [comment]
I would suggest one code base and add a build flag that enables the disco features. Have the build process generate both binaries and let the user choose from a drop down (one for vanilla ratgdo32 and one for disco).

**Comment by dkerr64** [comment]
> I would suggest one code base and add a build flag that enables the disco features. Have the build process generate both binaries and let the user choose from a drop down (one for vanilla ratgdo32 and one for disco).

I agree this would be ideal.  I'll look into it once things stabilize.  We have two quite different HomeKit libraries, so that will be the main issue to handle... I'd like to keep the ifdef's to a minimum.

**Comment by PaulWieland** [comment]
I wasn’t suggesting merging the v2.5x code into the v32 code (or back porting). I’m talking about one code base for both of the new ratgdo32 boards. The disco has the vehicle detection sensor, parking assist laser and beeper while the base board does not.

**Comment by dkerr64** [comment]
> I wasn’t suggesting merging the v2.5x code into the v32 code (or back porting). I’m talking about one code base for both of the new ratgdo32 boards. The disco has the vehicle detection sensor, parking assist laser and beeper while the base board does not.

Ah, I missunderstood.  Yes I have the same code base and with the next PR it will detect on startup whether there is a vehicle detection sensor or not so it will be the same binary for both.

**Comment by PaulWieland** [comment]
Nice! Okay I will update the instructions / links elsewhere for those looking for the HK Firmware.

**Pull request merged**
